/** Explicit SQL types; this manifest also describes empty generated tables. */
export const STUDY_SCHEMA = {
  bodies: {
    tick: "BIGINT",
    cell: "BIGINT",
    genome: "BIGINT",
    motor: "DOUBLE",
    core: "DOUBLE",
    speed_ceiling: "DOUBLE",
  },
  flows: {
    start_tick: "BIGINT",
    end_tick: "BIGINT",
    cell: "BIGINT",
    lineage: "BIGINT",
    genome: "BIGINT",
    channel: "VARCHAR",
    amount: "DOUBLE",
  },
  exposure: {
    start_tick: "BIGINT",
    end_tick: "BIGINT",
    cell: "BIGINT",
    lineage: "BIGINT",
    genome: "BIGINT",
    seconds: "DOUBLE",
    slowed_seconds: "DOUBLE",
    impaired_seconds: "DOUBLE",
    damage_seconds: "DOUBLE",
    swim_seconds: "DOUBLE",
    turn_seconds: "DOUBLE",
    food_read_seconds: "DOUBLE",
  },
  life: {
    tick: "BIGINT",
    cell: "BIGINT",
    parent: "BIGINT",
    lineage: "BIGINT",
    genome: "BIGINT",
    kind: "VARCHAR",
    x: "DOUBLE",
    y: "DOUBLE",
  },
  census: {
    tick: "BIGINT",
    cell: "BIGINT",
    lineage: "BIGINT",
    genome: "BIGINT",
    born: "BIGINT",
    generation: "BIGINT",
    x: "DOUBLE",
    y: "DOUBLE",
    energy: "DOUBLE",
    reserve: "DOUBLE",
    damage: "DOUBLE",
  },
  environment: {
    tick: "BIGINT",
    population: "BIGINT",
    grid_cells: "BIGINT",
    half_speed_area: "BIGINT",
    matrix: "DOUBLE",
    toxin: "DOUBLE",
    bound_toxin: "DOUBLE",
    energy_residual: "DOUBLE",
    material_residual: "DOUBLE",
  },
  genomes: {
    id: "BIGINT",
    parent: "BIGINT",
    born: "BIGINT",
    learned: "DOUBLE",
    encoding: "VARCHAR",
  },
} as const;
export type StudyTable = keyof typeof STUDY_SCHEMA;
export type StudyRow<T extends StudyTable> = {
  [K in keyof (typeof STUDY_SCHEMA)[T]]: number | string | null;
};
