use super::{display::ViewKey, runtime::Runtime, wire};
use antropy_engine::config::Config;
use serde_json::json;
use std::{path::Path, sync::Arc};

fn fixture() -> Runtime {
    Runtime::new(
        27,
        Config {
            width: 24.,
            height: 24.,
            founders: 4,
            source_count: 2,
            ..Config::default()
        },
        1,
    )
    .unwrap()
}
fn write_sample(
    path: &Path,
    label: &str,
    p: &super::runtime::Publication,
    w: &antropy_engine::world::World,
    key: ViewKey,
    previous: Option<&wire::Baseline>,
) -> wire::Baseline {
    let (packet, baseline) = wire::encode(p, key, 7, false, previous).unwrap();
    std::fs::write(path.join(format!("{label}.gz")), packet).unwrap();
    let scene = &p.scenes[&key];
    let organisms: Vec<_> = scene
        .organisms
        .iter()
        .map(|(id, a)| {
            let a = a.map(f32::from_bits);
            json!([*id, a])
        })
        .collect();
    let markers: Vec<_> = scene
        .markers
        .iter()
        .map(|(id, a)| json!([*id, a.map(f32::from_bits)]))
        .collect();
    let mut rendered = antropy_engine::render::Buffers::default();
    rendered
        .prepare_window(
            w,
            (key.kind, key.species, key.color, true, key.selected),
            key.window(w),
        )
        .unwrap();
    let environment: [Vec<f32>; 8] =
        std::array::from_fn(|lane| rendered.field.chunks_exact(8).map(|v| v[lane]).collect());
    std::fs::write(
        path.join(format!("{label}.json")),
        serde_json::to_vec(&json!({
            "status":*p.status,"organisms":organisms,"markers":markers,"environment":environment,
            "tick":p.tick,"generation":p.generation,"sequence":p.sequence,
        }))
        .unwrap(),
    )
    .unwrap();
    baseline
}

#[test]
#[ignore = "cross-language fixtures generated by the Vitest protocol test"]
fn export_transport_fixtures() {
    let output = std::env::var("BIOTROPY_TRANSPORT_FIXTURE").unwrap();
    let path = Path::new(&output);
    let mut r = fixture();
    let key = ViewKey::default();
    let p = r.publish(vec![key], 0.).unwrap();
    let baseline = write_sample(path, "initial", &p, &r.world, key, None);
    let p = r.publish(vec![key], 0.).unwrap();
    let baseline = write_sample(path, "unchanged", &p, &r.world, key, Some(&baseline));
    // Removed and inserted observations exercise identity, not vector-position matching.
    r.world.cells.swap_remove(1);
    r.world.cells[0].x = 23.9;
    r.world.step();
    r.world.incident.lateral = Arc::new([(0, 0.1234), (7, 0.008)].into());
    r.world.incident.emitters.insert(r.world.cells[0].id, 0.02);
    r.world.field.illumination.cover = Arc::new([(0, 0.6), (7, 0.4)].into());
    let shade = Arc::make_mut(&mut r.world.shade);
    shade.transmission.fill(0.8);
    shade.ceiling = vec![0.25; r.world.field.nx * r.world.field.ny];
    r.publish(vec![key], 0.).unwrap(); // Simulate a publication skipped behind backpressure.
    let p = r.publish(vec![key], 0.).unwrap();
    let baseline = write_sample(path, "changed", &p, &r.world, key, Some(&baseline));
    let sun_map = ViewKey { kind: 6, ..key };
    let p = r.publish(vec![sun_map], 0.).unwrap();
    let baseline = write_sample(path, "sun-map", &p, &r.world, sun_map, Some(&baseline));
    let cropped = ViewKey {
        viewport: Some([0, 0, 4, 6]),
        species: 1,
        ..key
    };
    let p = r.publish(vec![cropped], 0.).unwrap();
    let baseline = write_sample(path, "view", &p, &r.world, cropped, Some(&baseline));
    // Retention thinning and replacement of a point at the same tick.
    let mut p = r.publish(vec![cropped], 0.).unwrap();
    let status = Arc::make_mut(&mut p.status);
    status["history"] = json!([{"tick":0,"population":99},{"tick":1,"population":3}]);
    status["recent"] = json!([]);
    let baseline = write_sample(path, "history", &p, &r.world, cropped, Some(&baseline));
    r.replace(fixture().world).unwrap();
    let p = r.publish(vec![key], 0.).unwrap();
    write_sample(path, "replacement", &p, &r.world, key, Some(&baseline));
    write_sample(path, "reconnect", &p, &r.world, key, None);
}

#[test]
fn semantic_observations_match_local_renderer_and_preserve_physics() {
    let mut r = fixture();
    let before = r.world.snapshot().unwrap();
    let key = ViewKey::default();
    let p = r.publish(vec![key], 0.).unwrap();
    let scene = &p.scenes[&key];
    let mut buffers = antropy_engine::render::Buffers::default();
    buffers
        .prepare_window(
            &r.world,
            (key.kind, key.species, key.color, true, key.selected),
            key.window(&r.world),
        )
        .unwrap();
    assert_eq!(scene.organisms.len() * 12, buffers.cells.len());
    for record in buffers.cells.chunks_exact(12) {
        let a = scene.organisms[&(record[9] as u64)].map(f32::from_bits);
        assert_eq!(&a[..9], &record[..9]);
        assert_eq!(&a[9..], &record[10..]);
    }
    for (i, value) in buffers.field.iter().enumerate() {
        if i % 8 != 2 && i % 8 != 7 {
            assert_eq!(*value, f32::from_bits(scene.environment[i % 8][i / 8]));
        }
    }
    assert_eq!(r.world.snapshot().unwrap(), before);
}

#[test]
#[ignore = "bounded bandwidth mechanism check, explicitly invoked"]
fn incremental_bandwidth_probe() {
    bandwidth_case("ordinary", Config::ecology());
    let config = Config {
        features: antropy_engine::features::Features {
            photoreception: false,
            cover: false,
            emission: false,
            vocalization: false,
            strategy: false,
        },
        mortality_recovery: false,
        ..Config::ecology()
    };
    bandwidth_case("current-feature-switches", config);
}
fn bandwidth_case(label: &str, config: Config) {
    println!("case={label}");
    let mut r = Runtime::new(27, config, 4).unwrap();
    antropy_engine::commands::load_fixture(&mut r.world, 2000).unwrap();
    let key = ViewKey::default();
    let mut baseline: Option<wire::Baseline> = None;
    let mut raw = 0;
    let mut transmitted = 0;
    let started = std::time::Instant::now();
    for i in 0..6 {
        if i > 0 {
            for _ in 0..10 {
                r.world.step();
            }
        }
        let p = r.publish(vec![key], 30.).unwrap();
        if let Some(previous) = baseline.as_ref() {
            println!(
                "sections_organisms_markers_environment={:?}",
                p.scenes[&key].section_bytes(&previous.scene)
            );
        }
        let (bytes, next) = wire::encode(&p, key, 0, false, baseline.as_ref()).unwrap();
        let old = p.scenes[&key].raw_bytes()
            + p.status.to_string().len()
            + p.definition.to_string().len();
        if i > 0 {
            raw += old;
            transmitted += bytes.len();
        }
        println!(
            "sample={i} population={} legacy_bytes={old} incremental_bytes={}",
            r.world.cells.len(),
            bytes.len()
        );
        baseline = Some(next);
        assert!(started.elapsed().as_secs() < 120);
    }
    println!(
        "legacy_bytes={raw} incremental_bytes={transmitted} reduction={:.2} elapsed_seconds={:.3}",
        raw as f64 / transmitted as f64,
        started.elapsed().as_secs_f64()
    );
}
